#!/usr/bin/env node

var fs = require('fs');
var exec = require('child_process').exec;

/*

CSS-JSON Converter for JavaScript, v.1.0
By Aram Kocharyan, http://ak.net84.net/

Converts CSS to JSON and back.

*/

// String functions
var StringExtensions = new function() {
	// Added natively now
	this.trim = function() {
    	return this.replace(/^\s+|\s+$/g, '');
	};
	String.prototype.trim = this.trim;

	this.repeat = function(n) {
	    return new Array(1 + n).join(this);
	}
	String.prototype.repeat = this.repeat;
}

var CSSJSON = new function() {

	// These aren't used, just shown for convenience
	var selX = /([^\s\;\{\}][^\;\{\}]*)\{/g;
	var endX = /\}/g;
	var lineX = /([^\;\{\}]*)\;/g;
	var commentX = /\/\*.*?\*\//g;
	var lineAttrX = /([^\:]+):([^\;]*);/;

	// This is used, a concatenation of all above. We use alternation to capture.
	var altX = /(\/\*.*?\*\/)|([^\s\;\{\}][^\;\{\}]*(?=\{))|(\})|([^\;\{\}\/]+\;)/g;

	// Capture groups
	var capComment = 1;
	var capSel = 2
	var capEnd = 3;
	var capAttr = 4;

	// The main JSON converter function. Set keepOrder to true to keep order of comments etc.
	this.toJSON = function(css, keepOrder) {
		return getCSSRuleNode(css, keepOrder);
	}

	// Input is css string and current pos, returns JSON object
	var getCSSRuleNode = function(cssString, keepOrder) {
		var node = {};
		var match = null;
		var count = 0;

		while ( (match = altX.exec(cssString)) != null) {
			if (typeof match[capComment] != 'undefined') {
				// Comment
				var add = match[capComment].trim();
				node[count++] = add;
			} else if (typeof match[capSel] != 'undefined') {
				// New node, we recurse
				var name = match[capSel].trim();
				var newNode = getCSSRuleNode(cssString, keepOrder);
				if (keepOrder) {
					var obj = {};
					obj['name'] = name;
					obj['value'] = newNode;
					// Since we must use key as index to keep order and not name,
					// this will differentiate between a Rule Node and an Attribute,
					// since both contain a name and value pair.
					obj['type'] = 'rule';
					node[count++] = obj;
				} else {
					node[name] = newNode;
				}
			} else if (typeof match[capEnd] != 'undefined') {
				// Node has finished
				return node;
			} else if (typeof match[capAttr] != 'undefined') {
				var line = match[capAttr].trim();
				var attr = lineAttrX.exec(line);
				if (attr) {
					// Attribute
					var name = attr[1].trim();
					var value = attr[2].trim();
					if (keepOrder) {
						var obj = {};
						obj['name'] = name;
						obj['value'] = value;
						obj['type'] = 'attr';
						node[count++] = obj;
					} else {
						node[name] = value;
					}
				} else {
					// Semicolon terminated line
					node[count++] = line;
				}
			}
		}

		return node;
	}

	// The main CSS converter function.
	this.toCSS = function(json) {
		return strCSSRuleNode(json);
	}

	// Print a JSON node as CSS
	var strCSSRuleNode = function(node, level) {
		var cssString = '';
		if (typeof level == 'undefined') {
			level = 0;
		}
		for (i in node) {
			var subNode = node[i];
			if (typeof i == 'number' || parseInt(i) == i) {
				// Ordered
				if (typeof subNode == 'object') {
					if (subNode.type == 'rule') {
						// Selector
						cssString += strNode(subNode.name, subNode.value, level);
					} else {
						// Attribute
						cssString += strAttr(subNode.name, subNode.value, level);
					}
				} else {
					// Line/Comment
					cssString += '\t'.repeat(level) + subNode + '\n';
				}
			} else if (typeof i == 'string') {
				// Unordered
				if (typeof subNode == 'object') {
					// Selector
					cssString += strNode(i, subNode, level);
				} else {
					// Attribute
					cssString += strAttr(i, subNode, level);
				}
			}
		}
		return cssString;
	}

	// Helpers

	var strAttr = function(name, value, level) {
		return '\t'.repeat(level) + name + ': ' + value + ';\n';
	}

	var strNode = function(name, value, level) {
		var cssString = '\t'.repeat(level) + name + ' {\n';
		cssString += strCSSRuleNode(value, level+1);
		cssString += '\t'.repeat(level) + '}\n\n';
		return cssString;
	}

}

/*
* usage:
*   `lesswatch [lessc options] [-o output_dir] [src_dirs]
*
* examples:
*   `lesswatch`
*       to watch the current directory
*
*   `lesswatch -x`
*       to watch the current directory and pass the '-x' (minified css) option to lessc
*
*   `lesswatch path/to/dir`
*       to watch a directory
*
*   `lesswatch path/to/dir1 path/to/dir2`
*       to watch two (or more) directories
*
*   `lesswatch -o path/to/outdir path/to/dir1 path/to/dir2`
*       to watch two (or more) directories and output .css to another directory
*/


/**
* Compile a .less file to a .css file
*/
function compile(cssfile, outdir) {
  var outfile;
  var pathComponents = cssfile.split('/');
  fileName = pathComponents[pathComponents.length-1];

	if(typeof(outdir) !== 'string')
    outfile = cssfile.substr(0, cssfile.length-4) + "CSS.js";
  else
    outfile = outdir + '/' + fileName.substr(0, fileName.length - 4) + 'CSS.js';

  cssfile = cssfile.replace('//', '/');
  outfile = outfile.replace('//', '/');

  var css = fs.readFileSync(cssfile, 'utf8');
  var json = CSSJSON.toJSON(css);
  var jsonVar = "var " + fileName.substr(0, fileName.length - 4) + "CSS = "
                + JSON.stringify(json) + ";"
  fs.writeFileSync(outfile, jsonVar);
  console.log("Compiled " + cssfile + " to " + outfile);
}

function watchDir(path, outdir) {
	var files = fs.readdirSync(path);
	var prefix = path === '.' ? '' : (path + '/');
	for(var i in files) {
		var file = prefix + files[i];
		if(fs.statSync(file).isDirectory()) {
			// watch subdirectories recursively
			watchDir(file, outdir);
		} else {
			if(file.substr(-4) === '.css') {
				compile(file, outdir);
				fs.watchFile(file, function(fn, out, args){ return function(curr, prev){
					if(+curr.mtime !== +prev.mtime) {
						compile(fn, out, args);
					}
				}; }(file, outdir));
			}
		}
	}
}



/*************************/

var args = process.argv.slice(2);
var dirs = [];
var outdir = null;

if (args.length > 0) {
  for (var i = 0; i < args.length; i++) {
    if (args[i][0] !== '-')
      dirs.push(args[i]);
    else {
      if (args[i] === '-o' || args[i] === '--output') {
        if (i == args.length-1) {
          console.error('specify an output directory after -o or --output');
          process.exit(1);
        }
        else if (outdir !== null) {
          console.error('two output directories specified');
          process.exit(1);
        }
        outdir = args[++i];
      }
    }
  }
}

if (dirs.length == 0)
  dirs = ['.']

for(var i in dirs)
	watchDir(dirs[i], outdir);
